backend:
    image: 238991998648.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-backend
        tag: v1
          
          frontend:
              image: 238991998648.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-frontend
                  tag: v11
